### ISSUE TITLE
psxbuild.cpp does not compile

### ISSUE THREAD

**Issue by tatref** [cebix/psximager#2]
Using Ubuntu 14.04, gcc 4.8.2:

```
psxbuild.cpp: In function ‘int main(int, char**)’:
psxbuild.cpp:1096:26: error: request for member ‘len’ in ‘rootDirRecord.iso9660_dir_s::filename’, which is of non-class type ‘char [0]’
   rootDirRecord.filename.len = 1;
```

I commented that line (don't know the implication) to make it compile.

**Comment by MrSapps** [comment]
Wrong version of the iso9660 lib

**Comment by DavidGriffith** [comment]
I'd like to add that the versions of libcdio and libvcd present in Debian 9 are too old.  Neither are present in stretch-backports, so you'll need to make your own packages following this guide: https://wiki.debian.org/SimpleBackportCreation

You'll also need debhelper from stretch-backports and help2man from the regular stretch repository.

**Comment by tatref** [comment]
I managed to build using unstable Debian (Buster) all dependencies are standard, no custom library required.
I also created a Dockerfile for people using Docker

I merged the changes from:
* @gingerbeardman: typo for requirements
* @edmeme: fix for libcdio 2.0.0-1
* @cetygamer: Windows build instructions + makefile (not tested yet)

I also published static Linux binaries (usable without any libraries)

I tried to merge changes from @paulsapps (Travis / Appveyor), but the builds are currently failing.

See here: https://github.com/tatref/psximager

**Comment by gingerbeardman** [comment]
@tatref good news! I can build your version, but I'm still getting unexpected results 

will try your Linux version ASAP.

how is travis/appveyor failing? might be a clue for my problem

Mac (my build of your fork)
```
Analyzing image "pebble.cue"...
     LBN   NumSec     Size T Path
00000001 4158558d 00000000 d 
00000001 4158558d 00000000 f 
00000001 4158558d 00000000 f 
00000001 4158558d 00000000 f 
00000001 4158558d 00000000 f 
00000001 4158558d 00000000 f 
00000001 4158558d 00000000 f 
00000001 4158558d 00000000 f 
00000001 4158550d 00000000 f AT
00000001 4158558d 00000000 f 
00000001 4158558d 00000000 f 
00000001 4158558d 00000000 f 
00000001 4158550d 00000000 f NF
00000002 4158558d 00000000 f 
00000002 4158550d 00000000 f 
00000002 4158550d 00000000 f AT
00000003 4158550d 00000000 f AT
0000012e 4158550d 00000000 f .32
```

Windows ([this download of 2.0](http://www.romhacking.net/utilities/1404/))
```
Analyzing image "pebble.cue"...
     LBN   NumSec     Size T Path
00000016 00000001 00000800 d 
00000017 00000002 00000d64 f GAME.DAT
00000019 00000001 00000460 f MASTER.DAT
0000001a 00000002 00000870 f MEMBER.DAT
0000001c 00000003 0000172c f PEBBLE.DAT
0000001f 0000012e 00097000 f SLPS_006.32
0000014d 00000001 00000045 f SYSTEM.CNF
0000014e 00000001 00000800 d CADDIE
0000014f 00000348 001df100 x CADDIE/CADDIEA.STR
00000497 00000328 001ccd00 x CADDIE/CADDIEB.STR
000007bf 00000338 001d5f00 x CADDIE/CADDIEC.STR
00000af7 000004b8 002b0f00 x CADDIE/CADDIED.STR
00000faf 00000498 0029eb00 x CADDIE/CADDIEE.STR
00001447 00000358 001e8300 x CADDIE/CADDIEF.STR
0000179f 00000358 001e8300 x CADDIE/CADDIEG.STR
00001af7 00000378 001fa700 x CADDIE/CADDIEH.STR
00001e6f 000003c8 00228100 x CADDIE/CADDIEI.STR
00002237 000002e8 001a8500 x CADDIE/CADDIEJ.STR
(snip)
```

**Comment by tatref** [comment]
It seems that everything is messed up: sectors, size...
Do you have the same results on Linux with this ISO?

**Comment by gingerbeardman** [comment]
@tatref your Linux version is good

so my build is bad. maybe one of my dependencies is wrong?

Linux (your fork, release 3.0)
```
Analyzing image "pebble.cue"...
     LBN   NumSec     Size T Path
00000016 00000001 00000800 d 
00000017 00000002 00000d64 f GAME.DAT
00000019 00000001 00000460 f MASTER.DAT
0000001a 00000002 00000870 f MEMBER.DAT
0000001c 00000003 0000172c f PEBBLE.DAT
0000001f 0000012e 00097000 f SLPS_006.32
0000014d 00000001 00000045 f SYSTEM.CNF
0000014e 00000001 00000800 d CADDIE
0000014f 00000348 001df100 x CADDIE/CADDIEA.STR
00000497 00000328 001ccd00 x CADDIE/CADDIEB.STR
000007bf 00000338 001d5f00 x CADDIE/CADDIEC.STR
00000af7 000004b8 002b0f00 x CADDIE/CADDIED.STR
00000faf 00000498 0029eb00 x CADDIE/CADDIEE.STR
00001447 00000358 001e8300 x CADDIE/CADDIEF.STR
0000179f 00000358 001e8300 x CADDIE/CADDIEG.STR
00001af7 00000378 001fa700 x CADDIE/CADDIEH.STR
00001e6f 000003c8 00228100 x CADDIE/CADDIEI.STR
00002237 000002e8 001a8500 x CADDIE/CADDIEJ.STR
(snip)
```

**Comment by gingerbeardman** [comment]
My dependencies:
- libcdio 2.0.0
- vcdimager 2.0.1
- boost 1.67.0_1

My make output:
```
matt@MacBookPro-Matt:~/Downloads/2018-07-18/psximager-master$ make
Making all in src
g++ -DPACKAGE_NAME=\"PSXImager\" -DPACKAGE_TARNAME=\"psximager\" -DPACKAGE_VERSION=\"2.0\" -DPACKAGE_STRING=\"PSXImager\ 2.0\" -DPACKAGE_BUGREPORT=\"cb@cebix.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"psximager\" -DVERSION=\"2.0\" -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_FILESYSTEM=/\*\*/ -DHAVE_BOOST_REGEX=/\*\*/ -DHAVE_BOOST_SYSTEM=/\*\*/ -I.   -I/usr/local/Cellar/libcdio/2.0.0/include -I/usr/local/Cellar/libcdio/2.0.0/include -I/usr/local/Cellar/vcdimager/2.0.1/include -I/usr/local/Cellar/libcdio/2.0.0/include  -g -O2 -MT psxbuild.o -MD -MP -MF .deps/psxbuild.Tpo -c -o psxbuild.o psxbuild.cpp
mv -f .deps/psxbuild.Tpo .deps/psxbuild.Po
g++  -g -O2   -o psxbuild psxbuild.o -L/usr/local/Cellar/libcdio/2.0.0/lib -lcdio -lm -liconv -Wl,-framework,CoreFoundation -Wl,-framework,IOKit -Wl,-framework,DiskArbitration -L/usr/local/Cellar/libcdio/2.0.0/lib -liso9660 -liconv -lcdio -lm -liconv -Wl,-framework,CoreFoundation -Wl,-framework,IOKit -Wl,-framework,DiskArbitration -L/usr/local/Cellar/vcdimager/2.0.1/lib -L/usr/local/Cellar/libcdio/2.0.0/lib -lvcdinfo -liso9660 -lcdio -lm -liconv -Wl,-framework,CoreFoundation -Wl,-framework,IOKit -Wl,-framework,DiskArbitration -lboost_filesystem -lboost_regex-mt -lboost_system 
g++ -DPACKAGE_NAME=\"PSXImager\" -DPACKAGE_TARNAME=\"psximager\" -DPACKAGE_VERSION=\"2.0\" -DPACKAGE_STRING=\"PSXImager\ 2.0\" -DPACKAGE_BUGREPORT=\"cb@cebix.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"psximager\" -DVERSION=\"2.0\" -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_FILESYSTEM=/\*\*/ -DHAVE_BOOST_REGEX=/\*\*/ -DHAVE_BOOST_SYSTEM=/\*\*/ -I.   -I/usr/local/Cellar/libcdio/2.0.0/include -I/usr/local/Cellar/libcdio/2.0.0/include -I/usr/local/Cellar/vcdimager/2.0.1/include -I/usr/local/Cellar/libcdio/2.0.0/include  -g -O2 -MT psxinject.o -MD -MP -MF .deps/psxinject.Tpo -c -o psxinject.o psxinject.cpp
mv -f .deps/psxinject.Tpo .deps/psxinject.Po
g++  -g -O2   -o psxinject psxinject.o -L/usr/local/Cellar/libcdio/2.0.0/lib -lcdio -lm -liconv -Wl,-framework,CoreFoundation -Wl,-framework,IOKit -Wl,-framework,DiskArbitration -L/usr/local/Cellar/libcdio/2.0.0/lib -liso9660 -liconv -lcdio -lm -liconv -Wl,-framework,CoreFoundation -Wl,-framework,IOKit -Wl,-framework,DiskArbitration -L/usr/local/Cellar/vcdimager/2.0.1/lib -L/usr/local/Cellar/libcdio/2.0.0/lib -lvcdinfo -liso9660 -lcdio -lm -liconv -Wl,-framework,CoreFoundation -Wl,-framework,IOKit -Wl,-framework,DiskArbitration -lboost_filesystem -lboost_regex-mt -lboost_system 
g++ -DPACKAGE_NAME=\"PSXImager\" -DPACKAGE_TARNAME=\"psximager\" -DPACKAGE_VERSION=\"2.0\" -DPACKAGE_STRING=\"PSXImager\ 2.0\" -DPACKAGE_BUGREPORT=\"cb@cebix.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"psximager\" -DVERSION=\"2.0\" -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_FILESYSTEM=/\*\*/ -DHAVE_BOOST_REGEX=/\*\*/ -DHAVE_BOOST_SYSTEM=/\*\*/ -I.   -I/usr/local/Cellar/libcdio/2.0.0/include -I/usr/local/Cellar/libcdio/2.0.0/include -I/usr/local/Cellar/vcdimager/2.0.1/include -I/usr/local/Cellar/libcdio/2.0.0/include  -g -O2 -MT psxrip.o -MD -MP -MF .deps/psxrip.Tpo -c -o psxrip.o psxrip.cpp
mv -f .deps/psxrip.Tpo .deps/psxrip.Po
g++  -g -O2   -o psxrip psxrip.o -L/usr/local/Cellar/libcdio/2.0.0/lib -lcdio -lm -liconv -Wl,-framework,CoreFoundation -Wl,-framework,IOKit -Wl,-framework,DiskArbitration -L/usr/local/Cellar/libcdio/2.0.0/lib -liso9660 -liconv -lcdio -lm -liconv -Wl,-framework,CoreFoundation -Wl,-framework,IOKit -Wl,-framework,DiskArbitration -L/usr/local/Cellar/vcdimager/2.0.1/lib -L/usr/local/Cellar/libcdio/2.0.0/lib -lvcdinfo -liso9660 -lcdio -lm -liconv -Wl,-framework,CoreFoundation -Wl,-framework,IOKit -Wl,-framework,DiskArbitration -lboost_filesystem -lboost_regex-mt -lboost_system 
make[1]: Nothing to be done for `all-am'.
```

**Comment by cetygamer** [comment]
Hi, @tatref, if you have any questions regarding Windows build, I will be glad to help. I've been using psximager on Windows for the past 6 month with no issues.

**Comment by cebix** [comment]
I guess this can be closed.
